# mysql/docker-compose.yml
version: '3.8'

services:
  db:
    image: mysql:8.0
    ports:
      - '3307:3306'
    # environment:
    #   key: value
    #   MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    #   MYSQL_DATABASE: ${MYSQL_DATABASE}
    env_file:
      - .env
    networks:
      - db-connect
    volumes:
      #-  # Named Volume:[컨테이너 경로로]
      - db-volume:/var/lib/mysql

    # run -e MYSQL_ROOT_PASSWORD=1q2w3e4r!

# 컨테이너에 적용할 네트워크 드라이브를 관리하는 블록
networks:
  db-connect:

volumes:
  db-volume:
