export { default as logo } from '../assets/logo.svg';
export { default as home } from '../assets/home.svg';
export { default as contactUs } from '../assets/contactUs.svg';
export { default as contactUsColor } from '../assets/contactUsColor.svg';
export { default as kewordReview } from '../assets/keywordReview.svg';
export { default as kewordReviewColor } from '../assets/keywordReviewColor.svg';
export { default as markPool } from '../assets/markPool.svg';
export { default as markPoolColor } from '../assets/markPoolColor.svg';
export { default as mark } from '../assets/mark.svg';
export { default as markColor } from '../assets/markColor.svg';
export { default as more } from '../assets/more.svg';
export { default as myReview } from '../assets/myReview.svg';
export { default as myReviewColor } from '../assets/myReviewColor.svg';
export { default as mypage } from '../assets/mypage.svg';
export { default as mypageColor } from '../assets/mypageColor.svg';
export { default as noContent } from '../assets/noContent.svg';
export { default as pictureColor } from '../assets/pictureColor.svg';
export { default as profile } from '../assets/profile.svg';
export { default as swimming } from '../assets/swimming.svg';
export { default as wave } from '../assets/wave.svg';
export { default as kickPan} from '../assets/kickPan.svg';
export { default as xmark} from '../assets/xmark.svg';
export { default as back} from '../assets/back.svg';
